// Code generated by goctl. DO NOT EDIT!
// Source: category.proto

package server

import (
	"context"

	"iron-go/category/rpc/category"
	"iron-go/category/rpc/internal/logic"
	"iron-go/category/rpc/internal/svc"
)

type CategoryServer struct {
	svcCtx *svc.ServiceContext
}

func NewCategoryServer(svcCtx *svc.ServiceContext) *CategoryServer {
	return &CategoryServer{
		svcCtx: svcCtx,
	}
}

func (s *CategoryServer) GetList(ctx context.Context, in *category.Request) (*category.Response, error) {
	l := logic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *CategoryServer) Add(ctx context.Context, in *category.AddReq) (*category.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *CategoryServer) Del(ctx context.Context, in *category.DelReq) (*category.DelResp, error) {
	l := logic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *CategoryServer) GetTopList(ctx context.Context, in *category.GetTopListReq) (*category.GetTopListResp, error) {
	l := logic.NewGetTopListLogic(ctx, s.svcCtx)
	return l.GetTopList(in)
}

func (s *CategoryServer) GetCategoryById(ctx context.Context, in *category.GetCategoryByIdReq) (*category.GetCategoryByIdResp, error) {
	l := logic.NewGetCategoryByIdLogic(ctx, s.svcCtx)
	return l.GetCategoryById(in)
}
