// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserName   string `form:"userName"`   // 用户名
	Password   string `form:"password"`   // 密码
	RePassword string `form:"rePassword"` // 重复密码
}

type RegisterResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LoginReq struct {
	UserName string `form:"userName"` // 用户名
	Password string `form:"password"` // 密码
}

type LoginResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Resp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DeleteReq struct {
	Id int `form:"id"`
}

type AddCategoryReq struct {
	CatName     string `form:"catName"`
	ParentId    int    `form:"parentId"`
	Description string `form:"description,omitempty"`
}

type AddCategoryResp struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    AddCategoryData `json:"data"`
}

type AddCategoryData struct {
	Id int `json:"id"`
}

type ListCategoryReq struct {
}

type ListCategoryResp struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Data    []CategoryItem `json:"data"`
}

type CategoryItem struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}
