// Code generated by goctl. DO NOT EDIT!
// Source: category.proto

//go:generate mockgen -destination ./category_mock.go -package categoryclient -source $GOFILE

package categoryclient

import (
	"context"

	"iron-go/category/rpc/category"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	GetCategoryByIdResp = category.GetCategoryByIdResp
	AddReq              = category.AddReq
	AddResp             = category.AddResp
	DelReq              = category.DelReq
	DelResp             = category.DelResp
	GetTopListReq       = category.GetTopListReq
	GetTopListResp      = category.GetTopListResp
	Request             = category.Request
	Response            = category.Response
	CategoryItem        = category.CategoryItem
	GetCategoryByIdReq  = category.GetCategoryByIdReq

	Category interface {
		GetList(ctx context.Context, in *Request) (*Response, error)
		Add(ctx context.Context, in *AddReq) (*AddResp, error)
		Del(ctx context.Context, in *DelReq) (*DelResp, error)
		GetTopList(ctx context.Context, in *GetTopListReq) (*GetTopListResp, error)
		GetCategoryById(ctx context.Context, in *GetCategoryByIdReq) (*GetCategoryByIdResp, error)
	}

	defaultCategory struct {
		cli zrpc.Client
	}
)

func NewCategory(cli zrpc.Client) Category {
	return &defaultCategory{
		cli: cli,
	}
}

func (m *defaultCategory) GetList(ctx context.Context, in *Request) (*Response, error) {
	client := category.NewCategoryClient(m.cli.Conn())
	return client.GetList(ctx, in)
}

func (m *defaultCategory) Add(ctx context.Context, in *AddReq) (*AddResp, error) {
	client := category.NewCategoryClient(m.cli.Conn())
	return client.Add(ctx, in)
}

func (m *defaultCategory) Del(ctx context.Context, in *DelReq) (*DelResp, error) {
	client := category.NewCategoryClient(m.cli.Conn())
	return client.Del(ctx, in)
}

func (m *defaultCategory) GetTopList(ctx context.Context, in *GetTopListReq) (*GetTopListResp, error) {
	client := category.NewCategoryClient(m.cli.Conn())
	return client.GetTopList(ctx, in)
}

func (m *defaultCategory) GetCategoryById(ctx context.Context, in *GetCategoryByIdReq) (*GetCategoryByIdResp, error) {
	client := category.NewCategoryClient(m.cli.Conn())
	return client.GetCategoryById(ctx, in)
}
