// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	category "iron-go/internal/handler/category"
	user "iron-go/internal/handler/user"
	"iron-go/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/category/add",
				Handler: category.AddCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/category/list",
				Handler: category.ListCategoryHandler(serverCtx),
			},
		},
	)
}
