// Code generated by goctl. DO NOT EDIT!
// Source: training.proto

package server

import (
	"context"

	"iron-go/training/rpc/internal/logic"
	"iron-go/training/rpc/internal/svc"
	"iron-go/training/rpc/training"
)

type TrainingServer struct {
	svcCtx *svc.ServiceContext
}

func NewTrainingServer(svcCtx *svc.ServiceContext) *TrainingServer {
	return &TrainingServer{
		svcCtx: svcCtx,
	}
}

func (s *TrainingServer) Ping(ctx context.Context, in *training.Request) (*training.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *TrainingServer) Add(ctx context.Context, in *training.AddReq) (*training.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *TrainingServer) Get(ctx context.Context, in *training.GetReq) (*training.GetResp, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
