// Code generated by goctl. DO NOT EDIT!
// Source: movement.proto

package server

import (
	"context"

	"iron-go/movement/rpc/internal/logic"
	"iron-go/movement/rpc/internal/svc"
	"iron-go/movement/rpc/movement"
)

type MovementServer struct {
	svcCtx *svc.ServiceContext
}

func NewMovementServer(svcCtx *svc.ServiceContext) *MovementServer {
	return &MovementServer{
		svcCtx: svcCtx,
	}
}

func (s *MovementServer) Ping(ctx context.Context, in *movement.Request) (*movement.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *MovementServer) Add(ctx context.Context, in *movement.AddReq) (*movement.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *MovementServer) GetList(ctx context.Context, in *movement.GetListReq) (*movement.GetListResp, error) {
	l := logic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}
