// Code generated by goctl. DO NOT EDIT!
// Source: category.proto

package main

import (
	"flag"
	"fmt"

	"iron-go/category/rpc/category"
	"iron-go/category/rpc/internal/config"
	"iron-go/category/rpc/internal/server"
	"iron-go/category/rpc/internal/svc"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/category.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewCategoryServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		category.RegisterCategoryServer(grpcServer, srv)
	})
	defer s.Stop()
	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
